### ISSUE TITLE
Will you be incorporating the latest updates from NovelAI in the future?

### ISSUE THREAD

**Issue by ababxg** [bedovyy/ComfyUI_NAIDGenerator#12]
NovelAI has recently updated with some features similar to ControlNet. Will you be updating the nodes to include these?
At the same time, thank you very much for providing these nodes in ComfyUI.

**Comment by bedovyy** [comment]
do you mean https://docs.novelai.net/image/directortools.html ?
I will update it later. please wait with patient.

**Comment by ababxg** [comment]
> do you mean https://docs.novelai.net/image/directortools.html ?您的意思是https://docs.novelai.net/image/directortools.html吗？ I will update it later. please wait with patient.我稍后会更新。请耐心等待。

Yes,Thank you.

**Comment by bedovyy** [comment]
I added director tools. 659ccf513ec8c12b9b32aa1dbc2d7ab6dae1280f
Please check and let me know if there are any problem.

Thank you!
