### ISSUE TITLE
Furry v3?

### ISSUE THREAD

**Issue by Dibucci** [bedovyy/ComfyUI_NAIDGenerator#14]
Just started using this today when I was looking up ways to use NAI in a webui so i can gen an image then use a different model to add more detail to said image generated by NovelAI. Took me a bit to figure out the env, and this works amazingly.

However, I have noticed that the nai furry model seams.... different.. maybe... idk if its just my prompting or what but, is this using the new furry v3, or the old beta 1.3 model? the old beta model was SD1.4 and their new one is sdxl. it could just be me, and im not prompting right or something, but i just wanted to make sure

the only other reason i ask cuz other API's i found, like the one for A1111, uses the old beta 1.3 furry model

**Comment by Dibucci** [comment]
ok, after further investigation, doing the same seed and settings on both NAI's website and on the comfy UI node, it is indeed using the older version of NAI's Furry model... 😞 is there any Possible way to upgrade to the newest version of their furry model?

**Comment by bedovyy** [comment]
Thank you for reporting!
I have updated, so try it and let me know if there are another issues.

![image](https://github.com/user-attachments/assets/6fd0a7ce-4da1-4b54-8f34-1f9f4b751a1c)

**Comment by bedovyy** [comment]
I forget to tell you about quality and uc,
It works as actually add additional prompt to prompt or negative prompt.
However, the tags it added is different by model version or type. 
And, I couldn't test whether it remove duplicated prompt, or orders when user set quality preset or uc preset.

If you are interesting about actual tags for presets, Please refer the below.
https://github.com/Aedial/novelai-api/blob/ffd75ebb1c390153d193e7b66761a0de0cc452ea/novelai_api/ImagePreset.py#L146

**Comment by Dibucci** [comment]
ok, let me update the plugin and test this. tbh, was not expecting this fast of a reply. 😄 its kinda refreshing

**Comment by Dibucci** [comment]
currently im testing out different presets on the NAI website with the ones you have in that link for the furry v3 to see if ... i guess if they are working/bing used. Im using the same seed and paramaters as well... tho... im unsure what this "Limit_Opus_free" is? and idk if its causing the difference in chagnes im seeing....

hmm.... tried out heavy preset, light preset, and the "none" preset with the same prompt, seed, and settings.... however all 3 on NAI's website are comming out different compaired to what i have on comfyUI.... it is using their new model, that's the important part here (and ty again for adding it) but it does seam to be... different, or uses one of the presets constantly even if I put my own in.... or.... not....?

hmmm... im not the best at explaing things.... but l did the eevee prompt again to do a few tests on both the website and the comfyUI node, like in your image, i get the rock now on the bench next to eevee, but on novelAI, its slightly different with their being no rock and the bench legs being slightly different.... interesting.

it defently is pulling v3 but idk where these subtle changes are comming from cuz its not using the heavy, or light negative presets.... cuz the images im getting on NAI compared to comfy node, are drasticly different

I have just done the same prompt, seed, and setting on NAI for that eevee image and no matter what i set it to, i couldn't see it matching up to the image in comfy... its V3 for sure... im just curious as to what is going on that the outcomes are like 2 sides of a coin, completely different with the same stuff, and i cant tell if comfy is using the negative presets or no as when i use the presets on NAI, none give the comfyUI output if i leave the negative blank for it to use a preset

**Comment by Dibucci** [comment]
example, comfyui 
![image](https://github.com/user-attachments/assets/5434092e-b6b6-4ee5-8c33-30610dfc16cb)

and NAI with the same using the different presets starting with none, then light, then heavy
![image](https://github.com/user-attachments/assets/b179e3e5-8830-4522-9ffb-9899c6d88d2e)
![image](https://github.com/user-attachments/assets/8780821f-2e2d-4b02-8a55-b4ee417fb969)
![image](https://github.com/user-attachments/assets/6c42b98f-3d39-46d4-aa97-f0e92b0986bc)
i did it again with the added quality tags switch but it was just a slight change of each

the good thing is that it's working, and these changes are not bad... just... confusing why there is such a drastic change if its mostly using the api to use their stuff on local

**Comment by bedovyy** [comment]
I just noticed there is 'decrisper' setting on NAI webpage.
I add this on the node.

Now, I could get exactly same image with heavy uc.

workflow included image
![ComfyUI_27098_](https://github.com/user-attachments/assets/7cdde03e-cee6-4baa-b27b-7808017fbe35)

**Comment by Dibucci** [comment]
sorry for late response, day got busy not long after my last post. 

ill update it here shortly then. Also, ya, the slight difference was never a bad thing, i was just haveing a hard time figuring out why it was so different when using the different presets on the website compaired to the node, trying to figure out what it was using by default. 

However, now i feel kinda dumb not checking the meta data of the comfy UI image xD

I forget sometimes about the meta data in SD WebUI Images, and it completely slipped my mind

**Comment by Dibucci** [comment]
ty again btw for adding this. it makes things a lot eaiser having to do everything in one place since before this i had to make an image on NAI then copy/paste the image into comfy UI to do a slight i2i and upscale to add a bit more detail/texture/ect.
