### ISSUE TITLE
Wild cards

### ISSUE THREAD

**Issue by ajayeola** [bedovyy/ComfyUI_NAIDGenerator#16]
Does it support wildcards? I've never used comfy before and I'm thinking of trying out

**Comment by bedovyy** [comment]
You can use custom node like [impack pack](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md), after `convert widget to input` positive prompt.

![image](https://github.com/user-attachments/assets/add71cd9-47f2-4abf-94fb-60cdf5ea2fbe)
