### ISSUE TITLE
Director Tools관련 노드의 limit opus free기능이 작동하지 않습니다.

### ISSUE THREAD

**Issue by Clelstyn** [bedovyy/ComfyUI_NAIDGenerator#17]
1024 * 1024 이상의 픽셀을 가진 해상도의 이미지를 로드해서 Director Tools노드를 사용하면 limit opus free 체크 여부와 관계없이 pixel_limit가 정의되지 않았다는 오류가 발생합니다.

nodes.py를 살펴보니 base_augment함수에서 limit_opus_free가 사용되지 않고있고, pixel_limit가 정의되어있지 않습니다.

272라인의

    if w * h > 1024 * 1024:
        w, h = calculate_resolution(pixel_limit, (w, h))

를 다음과 같이 수정 요청합니다.

    if limit_opus_free:
        pixel_limit = 1024 * 1024
        if w * h > pixel_limit:
            w, h = calculate_resolution(pixel_limit, (w, h))

테스트후 정상작동 확인하였습니다.

**Comment by bedovyy** [comment]
추석 전후로 정신이 없어 이제서야 수정했네요.
리포트 감사합니다!
