### ISSUE TITLE
不知道怎么填写token

### ISSUE THREAD

**Issue by time-hurry** [bedovyy/ComfyUI_NAIDGenerator#24]
comfyui目录下没有.env的文件

**Comment by bedovyy** [comment]
You should make `ComfyUI/.env` file like
```
NAI_ACCESS_TOKEN=pst-123456789abcdef
```
After "NAI_ACCESS_TOKEN=", you need to paste your token.

You can get your token as following guide,
https://github.com/bedovyy/ComfyUI_NAIDGenerator?tab=readme-ov-file#setting-up-nai-account
