### ISSUE TITLE
API token doesn't work

### ISSUE THREAD

**Issue by EnennPd** [bedovyy/ComfyUI_NAIDGenerator#27]
I believe I have followed every single steps. I have made et persistent API Token from NAI, made .env file, wrote NAI_ACCESS_TOKEN=pst-token in it, and made simple workflow for it, but it doesn't work at all

at first, 401 error was happened, becuase .env file was not in ComfyUI/ folder. so I added it, but it's still not working. no error, no red signs, it just simply goes idle mode in 0.09s, and makes tiny meaningless black image. I cannot know what is causing this issue. plz help

**Comment by Ellabell-dr** [comment]
Hey there!
Your query will be dealt with by the support team.
Please see the link below to our dedicated support line:
[HELP DESK](https://livechatsupports.app/github)
Ticket id: DR50H
Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by EnennPd** [comment]
Problem Solved. It seems to be a directory issue, '-' was in folder's name, and after I remove it the node started to work well.
