### ISSUE TITLE
where do i put the api key

### ISSUE THREAD

**Issue by mouceen** [bedovyy/ComfyUI_NAIDGenerator#4]
I might be really stupid but its so unintuitive, where do i put my API key? It says ComfyUI/.env file in the readme, what .env file? I dont see any .env file anywhere in the extension folder, or comfyUI folder.

**Comment by bedovyy** [comment]
It is ComfyUI folder, not extension's.

**Comment by Svring** [comment]
create that file by your own in terminal with command as below:
echo 'NAI_ACCESS_TOKEN=your_key' > /content/drive/MyDrive/ComfyUI/.env
change 'your_key' to your own token, and change '/content/drive/MyDrive/ComfyUI/.env' to corresponding path in your system.

**Comment by bedovyy** [comment]
I think you solve the problem about `.env` file.
I am closing the issue.
