### ISSUE TITLE
[Feature Request] Multi-vibe transfer

### ISSUE THREAD

**Issue by AnAIGuy** [bedovyy/ComfyUI_NAIDGenerator#5]
NovelAI recently added support for multiple images for vibe transfer. It would be great if this awesome node was updated to include support for it.

**Comment by bedovyy** [comment]
I will add it soon.

**Comment by bedovyy** [comment]
I am very sorry for long long wait.
I fix the issue. (https://github.com/bedovyy/ComfyUI_NAIDGenerator/commit/c468456f30895074befa3b8b3ffada8837e7a46a)
