### ISSUE TITLE
[Feature Request] Automatically Retry

### ISSUE THREAD

**Issue by moon90175** [bedovyy/ComfyUI_NAIDGenerator#7]
Currently, when a request fails, such as Error 429, Comfy UI keeps reporting errors and hundreds of Queues are lost.
It would be nice to have a feature like Webui's NAI extension that automatically retries after a period of time when a request fails.

**Comment by bedovyy** [comment]
So sorry for long wait.
I change the code and it seems wokring. (https://github.com/bedovyy/ComfyUI_NAIDGenerator/commit/0d4c5c172ae53143cfcc1ef73a0f00e29981bbb3)

Please let me know if there's any problem.
